### ISSUE TITLE
Plugin doesn't see jar files

### ISSUE THREAD

**Issue by DmytroRybka** [satr/intellij-idea-plugin-connector-for-aws-lambda#2]
When I generate a jar file plugin cannot see it after refresh. 
![image](https://user-images.githubusercontent.com/437951/33939267-d1afce0e-e00a-11e7-8854-bbd7099258a8.png)

**Comment by satr** [comment]
Hi
Please check if the JAR file exists - on the disk and in the project tree:
![idea-jar-artifact-settings](https://user-images.githubusercontent.com/702860/34069006-793efc0e-e258-11e7-8000-dbae1b4b2743.jpg)
![idea-jar-artifact-in-project-tree](https://user-images.githubusercontent.com/702860/34069007-7a0027ee-e258-11e7-8187-3a303a6e4dbd.jpg)
I see some issues with updates of the JAR-artifact list when there is an error during access to resources and I will look at it also.

**Comment by satr** [comment]
Added a message to the logging, when there is no JAR-artefacts configured or JAR-file does not exist.
![log-message-not-found-jar](https://user-images.githubusercontent.com/702860/36182472-16600a32-112a-11e8-92d4-097b6fda224b.jpg)
Fixed in the [version v1.3](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/releases/tag/v1.3)
